@startuml
'https://plantuml.com/sequence-diagram

autonumber

'鉴权服务器初始化
鉴权服务器 -> 鉴权数据库: 内置数据库启动
鉴权服务器 -> 内置数据库初始化线程: 启动
内置数据库初始化线程 -> 鉴权数据库: 连接
鉴权数据库 --> 内置数据库初始化线程: 验证数据库账号密码
内置数据库初始化线程 --> 鉴权数据库: 响应数据库账号密码
内置数据库初始化线程 -> 鉴权数据库: 初始化数据库
内置数据库初始化线程 -> 内置数据库初始化线程: 结束线程
鉴权服务器 -> 监听线程: 启动
'鉴权服务器初始化结束


鉴权客户端 -> 监听线程: 连接
监听线程 -> 分类线程: 启动
鉴权客户端 -> 分类线程: {"type": XXXX} 发送链接类型
分类线程 -> 服务线程: 启动对应服务线程
分类线程 -> 分类线程: 结束线程
服务线程 -> 登录系统: 启动
登录系统 --> 鉴权客户端: Login.ASK_DATA 请求数据
鉴权客户端 --> 登录系统: Login.ACK_DATA 响应数据
登录系统 -> 鉴权数据库: 连接
鉴权数据库 --> 登录系统: LOGIN.ASK_DATA 验证数据库账号密码
登录系统 --> 鉴权数据库: LOGIN.ACK_DATA 响应数据库账号密码
登录系统 -> 鉴权数据库: 查找客户端提供的数据中的uuid
鉴权数据库 --> 登录系统: 响应uuid下的所有数据
登录系统 --> 服务线程: 相应用户登录状态以及所有登录数据




@enduml
